steps:
  - command: "install_bazel.sh"
    key: "install_bazel"
  - command: "bazel build //..."
    key: "bazel_build"
    depends_on: "install_bazel"
  - command: "bazel test //..."
    key: "bazel_test"
    depends_on: "bazel_build"
    retry:
      automatic:
        - exit_status: "*"
          limit: 5
