steps:
  #  - agents: { queue: "default" }
  #    command:
  #      - "export BUILDKITE_ANALYTICS_TOKEN=$$(buildkite-agent secret get test_suit_api_token)"
  #    key: "set_test_suit_api_token"
  #  - command: "install_bazel.sh"
  #    key: "install_bazel"
  - command: "bazel build //..."
    key: "bazel_build"
  - command: "bazel test --test_output=all //..."
    key: "bazel_test"
    depends_on: "bazel_build"
    retry:
      automatic:
        - exit_status: "*"
          limit: 5
  - command: "python xml_to_json_converter.py"
    key: "upload_to_test_engine"
    label: ":Upload to TestEngine:"
    depends_on: "bazel_test"
    plugins:
      - test-collector#v1.10.1:
          files:
            - "test-data-*.json"
          format: "json"
          debug: true
