steps:
  - command: "install_bazel.sh"
    key: "install_bazel"
  - command: "bazel build //..."
    key: "bazel_build"
    depends_on: "install_bazel"
  - commands:
      - "export BUILDKITE_ANALYTICS_TOKEN=$(buildkite-agent secret get test_suit_api_token)"
      - "echo $BUILDKITE_ANALYTICS_TOKEN"
    key: "set_test_suit_api_token"
    depends_on: "install_bazel"
  - command: "bazel test --test_output=all //..."
    key: "bazel_test"
    depends_on: "set_test_suit_api_token"
    plugins:
      - test-collector#v1.10.1:
          files:
            - "test-data-*.json"
          format: "json"
#    retry:
#      automatic:
#        - exit_status: "*"
#          limit: 5