steps:
  #  - agents: { queue: "default" }
  #    command:
  #      - "export BUILDKITE_ANALYTICS_TOKEN=$$(buildkite-agent secret get test_suit_api_token)"
  #    key: "set_test_suit_api_token"
  #  - command: "install_bazel.sh"
  #    key: "install_bazel"
  - command: "bazel --output_base=/tmp/bazel/ build //..."
    key: "bazel_build"
  - command: |
       bazel --output_base=/tmp/bazel/ test --test_output=all //... ;
       python --version ;
       python ./xml_to_json_converter/xml_to_json_converter.py ;
       ls /tmp/bazel/
    soft_fail:
      - exit_status: 3
    key: "bazel_test"
    depends_on: "bazel_build"
#    retry:
#      automatic:
#        - exit_status: "*"
#          limit: 2
    plugins:
      - test-collector#v1.10.1:
          files:
            - "test-data-*.json"
          format: "json"
          debug: true
