py_test(
    name = "test_flaky_low",
    timeout = "short",
    srcs = ["test_flaky_low.py"],
)

py_test(
    name = "test_flaky_mid",
    timeout = "short",
    srcs = ["test_flaky_mid.py"],
)

py_test(
    name = "test_flaky_high",
    timeout = "short",
    srcs = ["test_flaky_high.py"],
)

py_test(
    name = "test_reference",
    timeout = "short",
    srcs = ["test_reference.py"],
)
